language: java
deploy:
  provider: openshift
  user: pg8p@virginia.edu
  password: mesosecure
  app: claire
  domain: csgov-osedemo.com
  on:
    repo: pavgup/claire
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
